apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: promote-liberty-app
spec:
  inputs:
    resources:
      - name: image
        type: image
    params:
      - name: APP_NAME
        description: The name of the application
        default: 'liberty-tekton'
        type: string
      - name: APP_VERSION
        description: The version of the application
        default: '1.0'
        type: string
      - name: DEPLOY_PROJECT
        description: The project where you deploy the app
        default: 'env-dev'
        type: string
      - name: PROMOTE_PROJECT
        description: The project where you deploy the app
        default: 'env-test'
        type: string  
  steps:
      - name: create-app
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc tag $(inputs.params.DEPLOY_PROJECT)/$(inputs.params.APP_NAME):latest $(inputs.params.PROMOTE_PROJECT)/$(inputs.params.APP_NAME):latest
            oc tag $(inputs.params.PROMOTE_PROJECT)/$(inputs.params.APP_NAME):latest $(inputs.params.PROMOTE_PROJECT)/$(inputs.params.APP_NAME):$(inputs.params.APP_VERSION)
            oc get dc $(inputs.params.APP_NAME) -n $(inputs.params.PROMOTE_PROJECT)
            if [[ $? -ne 0 ]]
            then
                oc new-app -i $(inputs.params.PROMOTE_PROJECT)/$(inputs.params.APP_NAME):$(inputs.params.APP_VERSION) -n $(inputs.params.PROMOTE_PROJECT)
            else
                echo "Application already exists.Promoting version=$(inputs.params.APP_VERSION)"
                oc set image dc/$(inputs.params.APP_NAME) ${APP_NAME}=$(inputs.params.PROMOTE_PROJECT)/$(inputs.params.APP_NAME):$(inputs.params.APP_VERSION) --source=imagestreamtag -n $(inputs.params.PROMOTE_PROJECT)
            fi
      - name: expose-app
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc get svc $(inputs.params.APP_NAME) -n $(inputs.params.PROMOTE_PROJECT)
            if [[ $? -ne 0 ]]
            then
                oc expose svc/$(inputs.params.APP_NAME) -n $(inputs.params.PROMOTE_PROJECT)
            else
                echo "Application is already exposed."
            fi
      - name: set-app-labels
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc label dc/$(inputs.params.APP_NAME) app.kubernetes.io/name=java --overwrite -n $(inputs.params.PROMOTE_PROJECT)
            oc label dc/$(inputs.params.APP_NAME) app.version=$(inputs.params.APP_VERSION) --overwrite -n $(inputs.params.PROMOTE_PROJECT)
            oc set env dc/$(inputs.params.APP_NAME) app.version=$(inputs.params.APP_VERSION) -n $(inputs.params.PROMOTE_PROJECT)
      - name: set-app-probes
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc set probe dc/$(inputs.params.APP_NAME) --remove --readiness --liveness -n $(inputs.params.PROMOTE_PROJECT)
            oc set probe dc/$(inputs.params.APP_NAME) --readiness --get-url=http://:9080/ --initial-delay-seconds=30 -n $(inputs.params.PROMOTE_PROJECT)
      - name: set-app-autoscale
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc get hpa $(inputs.params.APP_NAME) -n $(inputs.params.PROMOTE_PROJECT)
            if [[ $? -ne 0 ]]
            then
                oc autoscale dc $(inputs.params.APP_NAME) --min 1 --max 2 --cpu-percent=75 -n $(inputs.params.PROMOTE_PROJECT)
            else
                echo "Application autoscale is already configured."
            fi
      - name: describe-app-triggers
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc set triggers dc/$(inputs.params.APP_NAME) -n $(inputs.params.PROMOTE_PROJECT)